### ISSUE TITLE
Can I use this plugin to debug a "polymer web component"?

### ISSUE THREAD

**Issue by raghav135** [Microsoft/vscode-chrome-debug#108]
I am not able to understand how to use vscode chrome debug for debugging "polymer web components"  for 2 reasons:

1. Polymer uses its own "polyserve" utility which does below:
        a. If my project workspace is d:/abc , it will be rendered as "localhost:8080/components/abc"
        b. the bower_components folder contents will be rendered within "localhost:8080/components/".
     I dont know what should be the webroot in launch.json...

2. In Polymer, the js code is generally within the html file of the web component. I am not able to add a breakpoint within embedded script tag of the html.

Request your help.

**Comment by roblourens** [comment]
If you don't want to debug the source for your bower_components, you can set it up normally for the /components/abc folder. Otherwise, it sounds like you would need to map multiple paths to multiple source folders, which is covered by #86 .

I just filed #122 to cover the second, but we don't allow setting breakpoints in embedded scripts yet.
