### ISSUE TITLE
Support debugging "Just my code"

### ISSUE THREAD

**Issue by maxhor** [Microsoft/vscode-chrome-debug#137]
When setting a breakpoint in typescript and then stepping through code, (either step over, step into, step out):  I will end up in the javascript code that was generated from the typescript or in the code from libraries under node_modules (like Angularjs). 

How can I change the settings so that when debugging my code, everything besides the typescript that I wrote myself is stepped over?

**Comment by roblourens** [comment]
You're describing a feature called "Just My Code" in F12 or "blackbox scripts" in Chrome Devtools. We could probably implement that but haven't yet.

**Comment by maxhor** [comment]
ok, 

But I think I am missing something. 

If I set a breakpoint in my .ts code, I am complete lost after 2 or 3 steps. Not only will I hit the js file that goes with the ts file (I could maybe cope with that) But in a few steps I am in the middle of system.src.js, angular2.dev.js or angular2.polyfills.js.

I'd say there's more people then just me that will be lost when they end up in angular2.polyfills.js. 

So what does one do to make debugging workable?

**Comment by maxhor** [comment]
I don't use webpack. javascript lines should have TS associated, so I attach the log ( am I right that I can only copy what is visible from the console ?)

[log.txt](https://github.com/Microsoft/vscode-chrome-debug/files/197051/log.txt)
 
I ' launched'  the debugger, here is associated launch.json:

```
{
			
            
            "name": "Launch index.html",
			"type": "chrome",
			"request": "launch",
            "file": "index.html",
            "runtimeArgs":["--allow-file-access-from-files"],
            "sourceMaps":true,
            "diagnosticLogging": true,
            // "outDir":null,
            // "address":"localhost",
            // "program":null,
            // "stopOnEntry":false,
            // "args":null,
            "cwd": "${workspaceRoot}",
            "runtimeExecutable":null
		},
```

**Comment by roblourens** [comment]
Probably not in the really near future, got other stuff to do first. Thanks for the annotated log. Yeah, at the moment you can only copy the visible portion of the log. I'm not sure what's going on there. It looks like you step through lines 39, 40, and 41 (0-indexed) of the js file, then at line 41, it returns the js file in the stackTrace instead of the ts file. That would most likely happen because it can't resolve the sourcemap for that particular location. Can you share the project with me? Or just that file and its sourcemap (.js, .ts, and .js.map)?

**Comment by maxhor** [comment]
I share. I am not used to publish here, normally I am on Bitbucket. As you do not seem to have an account on bitbucket, I publish my project on github. Hope I did it right. Its called 'plunk'. (its just the sample project from Angular.io)

Project is not in exact same state as when I retrieved the log, Sorry for that. I watch that in future. But still, after some debuggung steps, debugging ends in .js.

**Comment by roblourens** [comment]
Thanks. Looks like the exact lines you were debugging aren't the same now, so I can't tell you whether that was right or not. I always step into JS eventually but it's either because it's an angular file, or a line that doesn't have a mapping in TS. Like sometimes I step into the decorators. So there's not much you can do about that.

**Comment by roblourens** [comment]
This issue was moved to Microsoft/vscode-chrome-debug-core#7
