### ISSUE TITLE
Source maps not reloading

### ISSUE THREAD

**Issue by joewood** [Microsoft/vscode-chrome-debug#152]
When using **webpack-dev-server** and source maps everything works fine until a change in the source file causes the modules to be repackaged. The debugger uses the source maps from the first package and doesn't reload them. This causes breakpoints to be off by a few lines. Stop and restarting debugging fixes the issue.

Is there anyway of forcing source maps to reload from the **webpack-dev-server** without restarting the debugger? 

I've been using the vscode-chrome-debugger since it was released (it's great) but only noticing this problem recently.

**Comment by roblourens** [comment]
Does webpack-dev-server cause the browser to refresh the page, or do something smarter? Does refreshing the page fix it?

Is it possible that the file is being cached by the browser?

Does it work in Chrome devtools?

**Comment by joewood** [comment]
Hi @roblourens yes - webpack-dev-server causes the page to refresh (hotloading is disabled for this app). Refreshing the page doesn't fix it. And dev tools works fine, the source map is adjusted corrected.

**Comment by Mr-AK** [comment]
I have same issue. **vscode** is kept attached to the browser while **webpack-dev-server** do rebuild and reload on source change. Making breakpoint stop and stepping through the code shows incorrect lines. It looks like **vscode** is unaware of the page reload. In my configuration **webpack-dev-server** saves bundles and map files on disk where **vscode** finds them. Restart debugger solves the problem.
There is no such issue when using dev. tools inside Chrome (instead of **vscode**).

**Comment by savpek** [comment]
Same also occurs with angular 2 cli v.1.0.0-beta.22-1, probably repros with all version which use web-pack bundling behind scenes.
