### ISSUE TITLE
Unable to Set Breakpoints

### ISSUE THREAD

**Issue by seansellek** [Microsoft/vscode-chrome-debug#179]
I am unable to set breakpoints. Breakpoints show as "unverified breakpoint" and do not trigger. 

VSCode is successfully connecting to chrome, as I can see it's output in the debug console. 

Source maps are also working, as I can work with breakpoints just fine from Chrome itself.

Let me know what other information I can provide!

![screenshot 2016-06-18 19 11 06](https://cloud.githubusercontent.com/assets/1727840/16174262/71076662-3588-11e6-8026-abe99de8c353.png)

**Comment by auchenberg** [comment]
Can you share your `launch.json` config? It's probably a problem with your `webRoot` property that causes the debugger to fail mapping your local source to the sourcemapped files.

**Comment by seansellek** [comment]
Here's my launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
      {
            "name": "launch with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "runtimeExecutable": "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
            "runtimeArgs": [ "--remote-debugging-port=9222" ],
            "url": "http://localhost:4200/",
            "webRoot": "${workspaceRoot}/app",
            "port": 9222,
            "sourceMaps": true
        }
    ]
}
```

I've tried both with `"${workspaceRoot}/app"` as well as the default `"${workspaceRoot}`. Here's a screenshot showing my workspace folder:

![screenshot 2016-06-18 19 35 42](https://cloud.githubusercontent.com/assets/1727840/16174351/dba86c84-358b-11e6-9961-7915c2e7344f.png)

**Comment by auchenberg** [comment]
That's interesting. Can you set `"diagnosticLogging"` flag to `true` in your `launch.json` and copy/paste the full log in here? Looks like the debugger aren't able to map/parse the sourcemap. There should be some useful logs when the page is loaded, and when you try to toggle a breakpoint.

Thanks, and sorry for the trouble!

**Comment by auchenberg** [comment]
Also it be good to know more about you setup, as we might be the flavor of source map generated that's causing problems. Looks like you are using ES2016, so you have babel and maybe webpack in place?

**Comment by roblourens** [comment]
Does `/dist` contain your built files? Your webRoot may need to be set at /dist instead of /app. Also you can copy the log file from `~/.vscode/extensions/vscode-chrome-debug` when diagnosticLogging is enabled.

**Comment by seansellek** [comment]
Alright so I set the webRoot to `/dist` (according to Ember docs, it does contain my built files) and copied the full log to [here](https://gist.github.com/seansellek/06b1dd54033b7b66c5f29467eb379fab)

I can see in line 18 where the breakpoint is failing because "SourceMaps.setBP: /Users/Sean/OneDrive/Wyncode/placements/app/helpers/get-attribute.js can't be resolved to a loaded script. It may just not be loaded yet."

I can also see some warnings around lines 31-44 regarding my SourceMaps being inlined?

The results are very similar with `/app` as my webRoot, I pasted the logs [here](https://gist.github.com/seansellek/8937e365b15d2ed03666cbcf5938f36f)

I do have babel, but not webpack. Huge thank you!

**Comment by roblourens** [comment]
So the source file is here -
`From client: setBreakpoints({"source":{"path":"/Users/Sean/OneDrive/Wyncode/placements/app/helpers/get-attribute.js"},"lines":[5],"breakpoints":[{"line":5}]})`

Then later it is creating the sourcemap for placements.js, and there is no sourceRoot -
```
SourceMap: creating for /Users/Sean/OneDrive/Wyncode/placements/dist/assets/placements.js
SourceMap: sourceRoot: undefined
SourceMap: sources: [ ... placements/helpers/get-attribute.js ]
```

So it's resolved incorrectly
`SourceMaps.scriptParsed: /Users/Sean/OneDrive/Wyncode/placements/dist/assets/placements.js was just loaded and has mapped sources: [ ... /Users/Sean/OneDrive/Wyncode/placements/dist/assets/placements/helpers/get-attribute.js`

So you will need to have set sourceRoot (in the sourcemap file) set so that vscode can find the sources on disk. How you do that depends on your build config, but it needs to be either a relative path from the script or a url.

**Comment by auchenberg** [comment]
Looks like `ember-cli` previously didn't set the `sourceRoot`-attribute in the generated source maps. Don't know if that still is the case, https://github.com/ember-cli/ember-cli/issues/4369

**Comment by seansellek** [comment]
I just landed on that same issue after reading roblourens' reply. I'll continue looking into how Ember handles this, thanks to both of you for helping point me in the right direction! Sorry for the bother.

**Comment by roblourens** [comment]
No problem, hope it helps. It's not uncommon for tools to use inline sources, and not set up the paths correctly, especially when sources are outside of the directory that the webserver is serving. I think we can still do a better job of making that clear in our logging.

**Comment by seansellek** [comment]
Alright, I am successfully setting the sourceRoot, and it is being parsed by `vs-chrome-debug`, here are the [new logs](https://gist.github.com/seansellek/a0cfe10b24edad83017b2b5c5388b247)

Line 41 represents the correct mapping, but that is not being applied where it matters.

In line 36-38, it's not applying the entire path, for example `"placements/components/table-for.js"` should have been `"/Users/Sean/OneDrive/Wyncode/placements/app/components/table-for.js"`.

If the absolute path isn't necessary, there needs to be an app folder after the root project directory: `placements/app/components/table-for.js`.

I'm beginning to wrap my head around this more, and if the problem is in my court I will happily prepare guides to help develop with Ember.js and vscode-chrome-debug.

**Comment by roblourens** [comment]
Lines 36-38 are just dumping verbatim what's in the sourcemap file. You have sourceRoot: `/app` and an entry in sources like `placements/helpers/get-attribute.js`. So those get combined to `/app/placements/helpers/get-attribute.js`. Since it starts with /, it's resolved with the webRoot, `/Users/Sean/OneDrive/Wyncode/placements/`, to get `/Users/Sean/OneDrive/Wyncode/placements/app/placements/helpers/get-attribute.js` that you see on line 41, which doesn't match the actual source location, `/Users/Sean/OneDrive/Wyncode/placements/app/helpers/get-attribute.js`. 

So the sourceRoot + sources are wrong to start out with- you could try setting sourceRoot to `file:////Users/Sean/OneDrive/Wyncode` since it seems like that's what it wants to make the sources relative to.

**Comment by roblourens** [comment]
I'd love to have a working setup with Ember for our [Examples](https://github.com/Microsoft/vscode-chrome-debug/wiki/Examples) page!

**Comment by roblourens** [comment]
In case you were still looking at this, wanted to point out that it came up that Ember apparently doesn't always generate sourcemaps from the original ES6 source - https://github.com/ember-cli/ember-cli/issues/6066#issuecomment-232469330.
