### ISSUE TITLE
Add support of Meteor application (fetch source maps over HTTP, not filesystem)

### ISSUE THREAD

**Issue by tomitrescak** [Microsoft/vscode-chrome-debug#183]
Hi, this looks like a fantastic extension! Yet, it is not possible to use it with Meteor applications, since Meteor does not respect the directory hierarchy and generates source maps based on URL request.
As a result I get bunch of errors `SourceMaps.loadSourceMapContents: Could not read sourcemap from /packages/27b3d669b418de8577518760446467e6ff429b1e.map`

To explain better, source map `27b3d669b418de8577518760446467e6ff429b1e.map` does not exists physically on hard drive and can only be requested from server. As a result the extension fails. Is it possible to request source maps from server and not load them from the drive?

**Comment by auchenberg** [comment]
Interesting use-case of sourcemaps. Do you have any documentation on the Meteor setup?

**Comment by tomitrescak** [comment]
Unfortunately I don't. But it's easy to check.
1. Install meteor:
  `curl https://install.meteor.com/ | sh`
2. Create new app
   `meteor create testApp`
3. Run the app
    `cd testApp; meteor`

When you try to debug this application you will receive all the errors.

**Comment by roblourens** [comment]
It actually should be downloading the sourcemap, if it can't find it on disk. I'll try it out with meteor.

**Comment by roblourens** [comment]
The sourcemap's sources entry is `"meteor://💻app/client/main.js"`. Cute. I may add some hardcoded detection like for webpack, but something like Microsoft/vscode-chrome-debug-core#44 should also fix this.

**Comment by tomitrescak** [comment]
@roblourens can you please elaborate on how https://github.com/Microsoft/vscode-chrome-debug-core/issues/44 can fix this? Am a bit lost there. Thank you kindly for taking interest in this.

**Comment by roblourens** [comment]
Basically you need a way to map `meteor://...` to the real path, and that issue will let a user override the paths in the sourcemap. I'm not very familiar with Meteor, but if there's a way to get it to output sourcemaps with the proper `sources` or `sourceRoot` entries, then that would be a workaround for the meantime.

**Comment by abernix** [comment]
@roblourens I'm curious specifically what you believe is wrong with the `sources` in Meteor's source map.  I'm not at all familiar with Visual Studio Code and what it's trying to do, but I don't believe Meteor is wrong in it's implementation.

I'm basing my interpretations of the source map rules on what I believe is [the most official sourcemap spec](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit) and the [`source-map` npm module](https://github.com/mozilla/source-map/) from Mozilla.

About the Meteor source-map implementation:

* Uses `source-map` NPM internally.
* The source map is provided by the `X-SourceMap` header and points to a URL on the server to the actual JSON source map object.
 * Note: I realize that `X-SourceMap` has been deprecated in favor of `SourceMap`, but I don't believe that's the issue here, is it?
* `sources` use the `meteor://` URL scheme, but that is simply to keep the specific project files in their own neat organization structure using the :computer: icon.  These need not be fetched from the server at all since `sourcesContent` (below) is provided.
* `sourcesContent` array elements are provided and 1:1 mapped to the `sources` (above) to provide the actual file content without hosting them, per the spec:

 > Line 6: An optional list of source content, useful when the “source” can’t be hosted.

Really, it doesn't seem to matter what URL is provided by the `sources` as it is not necessary to fetch them. Does MS VSC try to map these to actual files within the editor itself?  If so, that's neat but it seems like it would be problematic since `sources` is permitted to be a list of absolute URLs.  Is there a map-to-local preference or something?

Things are interpreted correctly by the `source-map` NPM and Chrome Dev Tools works well, so I'm trying to grasp what the issue might be here and any help would be appreciated.

**Comment by roblourens** [comment]
Right, we try to map the source path to the file on disk, which is the extra complication. We have the same problem with webpack - they output URLs that start with `webpack://` and we ended up adding a little special handling to strip that. I'd rather not do that for every framework. I think webpack allows users to configure the sources format. If you can't do that in meteor, it would be great if that was an option.

But when I have time I'll implement Microsoft/vscode-chrome-debug-core#44 which would let users configure some mapping from a URL like `meteor://...` to a path on disk.

**Comment by auchenberg** [comment]
@abernix Our debugger tries to map the loaded source files from the browser to the files on disk, as that's the files you are editing within VS Code. 

That's what makes this debugger special, and how it's different from Chrome DevTools's usage of source maps.

**Comment by tomitrescak** [comment]
Is there any way I can hack this now? Can you just please point me towards the web pack hack? I just want to test the performance difference. Thanks.

**Comment by roblourens** [comment]
Open `~/.vscode/extensions/msjsdiag.debugger-for-chrome/out/src/sourceMaps/sourceMap.js`, look for 'webpack:///' and replace that with 'meteor:///<pc emoji>app'. I think that should do it. You may have to mess around with it.

I'm also working on Microsoft/vscode-chrome-debug-core#44, so you should have a better workaround in the very near future.

**Comment by roblourens** [comment]
In 0.4.7, Meteor sourcemaps should work by default! If your config is different, you can use the new `sourceMapPathOverrides` option in the launch config to get your sources matching what's on disk.
