### ISSUE TITLE
Investigate another webpack hack

### ISSUE THREAD

**Issue by ulitiy** [Microsoft/vscode-chrome-debug#187]
See #85, #40
I'm using webpack,
https://gist.github.com/ulitiy/f469b392cd2d803de93cdf7121886cf3 my configs
```
/Users/ulitiy/Dropbox/RAILS/aurora/node_modules/phaser/build/phaser.min.js
  ›SourceMap: sourceRoot: undefined
  ›SourceMap: sources: ["phaser.js"]
  ›SourceMap: webRoot: /Users/ulitiy/Dropbox/RAILS/aurora
  ›SourceMap: no sourceRoot specified, using script dirname: /Users/ulitiy/Dropbox/RAILS/aurora/node_modules/phaser/build
  ›SourceMaps.scriptParsed: /Users/ulitiy/Dropbox/RAILS/aurora/node_modules/phaser/build/phaser.min.js was just loaded and has mapped sources: ["/Users/ulitiy/Dropbox/RAILS/aurora/node_modules/phaser/build/phaser.js"]
  ›SourceMap: creating for http://localhost:8080/dist/bundle.js
  ›SourceMap: sourceRoot: 
  ›SourceMap: sources: ["webpack:///webpack/bootstrap 63ce91f60e62a590e8b0","webpack:///./src/index.ts"]
  ›Warning: SourceMap sources are inlined. This extension ignores inlined sources. If the paths are not correct, sourcemap support won't work.
  ›SourceMap: webRoot: /Users/ulitiy/Dropbox/RAILS/aurora
  ›SourceMap: no sourceRoot specified, using webRoot + script path dirname: /Users/ulitiy/Dropbox/RAILS/aurora/dist
  ›SourceMaps.scriptParsed: http://localhost:8080/dist/bundle.js was just loaded and has mapped sources: ["/Users/ulitiy/Dropbox/RAILS/aurora/dist/webpack/bootstrap 63ce91f60e62a590e8b0","/Users/ulitiy/Dropbox/RAILS/aurora/dist/src/index.ts"]
```

So it's trying to find the file in `/dist/src`, it should search in `/src` though.

If I specify `"sourceRoot": "/Users/ulitiy/Dropbox/RAILS/aurora/",`
webpack just doesn't start:
`Error: "src/index.ts" is not in the SourceMap.`

Thanks.

**Comment by roblourens** [comment]
So since there's no sourceroot, and the sources has `webpack:///./src/index.ts`, we strip `webpack:///` and resolve the source path relative to the sourcemap location, which is what the sourcemap spec says to do.

When you set the sourceRoot, where does that error come from? Does it work if you remove `/src/` from the sourceRoot (since it wants to include 'src' in the sources entry, apparently). That should be the right fix.

It's hard to know what to do here with webpack since they are kind of making this stuff up, but maybe we could try to resolve the path against the webRoot, in this specific case when the sources entry has `webpack:///`? I don't know whether that makes sense.

**Comment by ulitiy** [comment]
```
/usr/local/lib/node_modules/webpack/node_modules/webpack-core/lib/NormalModuleMixin.js:163
			if(isError) throw e;
			            ^
```

Adding/removing `/src/` doesn't change anything.
With `"sourceRoot": "/Users/ulitiy/Dropbox/RAILS/aurora/src",`
```
Error: "index.ts" is not in the SourceMap.
```
with `"sourceRoot": "/Users/ulitiy/Dropbox/RAILS/aurora",`
```
Error: "src/index.ts" is not in the SourceMap.
```

Probably I need to set `sourceRoot` to something but this webpack error isn't very verbose.

**Comment by ulitiy** [comment]
sorry, accidentally closed

**Comment by roblourens** [comment]
Huh, I'm not sure what webpack is trying to do there. And that's on the frontend, not webpack-dev-server?

I know that error is from the 'source-map' library which is very particular about how you refer to paths, so I'm guessing webpack just doesn't expect a sourceRoot to be set. 

I'll mark this as a bug to investigate what I said above ("maybe we could try to resolve the path against the webRoot, in this specific case when the sources entry has `webpack:///`"). I really want this to be usable with webpack. You might check out our example with webpack to see what the difference is with your setup - https://github.com/Microsoft/vscode-chrome-debug/wiki/Examples.

**Comment by ulitiy** [comment]
Yes, I'm trying to use `webpack-dev-server` but the same result with just launching `webpack`.
Your webpack example it doesn't use typescript and tsconfig.

**Comment by roblourens** [comment]
Yeah but it does use sourcemaps, and it should work with `devtool: source-map` like in your example too.

**Comment by roblourens** [comment]
Note to self, or anyone else - The reason the example works is that it uses webpack-dev-server and serves bundle.js as `localhost:3000/bundle.js`. And the sourcemap has the source paths relative to the project root, same as the scenario above. It doesn't actually exist on disk, but since we set the webRoot to `${workspaceRoot}`, we can resolve the source paths correctly. So... I think the fix above is the right fix.

Something like Microsoft/vscode-chrome-debug-core#44 would also help.

**Comment by roblourens** [comment]
In 0.4.7, this should actually work correctly. If not, you can use the new `sourceMapPathOverrides` option in the your config to get your sources to match what's on disk. Try it out and let me know!

**Comment by AlexanderMattoni** [comment]
I think I'm having a similar issue, but I'm not sure I understand the fix for this. My launch.json currently looks like the following:
![image](https://cloud.githubusercontent.com/assets/5110855/16703431/6333b12c-453b-11e6-87a0-48e4ab3733c5.png)

but I'm unable to set breakpoints, even though the pause functionality works just fine. How do I use the sourceMapPathOverrides option?

**Comment by roblourens** [comment]
There are some notes in the README which might help. Otherwise you need to look at the paths in your sourcemaps, figure out what they should be, and add a `sourceMapPathOverrides` option to fix it. I can help if you upload your `~/.vscode/extensions/msjsdiag.debugger-for-chrome/vscode-chrome-debug.txt` file here.

**Comment by AlexanderMattoni** [comment]
I would greatly appreciate the help! Let me know if you need anything else.
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/355261/vscode-chrome-debug.txt)

**Comment by roblourens** [comment]
Oh, it looks like you're a version behind :). Try updating for 0.4.7 and give it a shot.

**Comment by AlexanderMattoni** [comment]
That worked! Thanks so much this is great.

**Comment by mvidailhet** [comment]
OK, so after running on the same problems trying to debug our Ionic App, I had to add these lines to make it work:
```
"sourceMapPathOverrides": {
    "webpack:///./*":   "${cwd}/*",
    "webpack:///*":     "*",
},
```

It seems that the launch.json uses `cwd` instead of `webRoot`

**Comment by roblourens** [comment]
Yeah cwd also will be replaced, webRoot should also work if its set to the same thing.
