### ISSUE TITLE
Support Stetho targets

### ISSUE THREAD

**Issue by cpetrov** [Microsoft/vscode-chrome-debug#188]
Stetho target items have type `app` instead of `page`. Currently only `page` type is allowed: https://github.com/Microsoft/vscode-chrome-debug/blob/master/src/chromeDebug.ts#L11

Example */json* service response of a Stetho target:
```js
[
    {
        "type": "app",
        "title": "App Name (powered by Stetho)",
        "id": "1",
        "description": "",
        "webSocketDebuggerUrl": "ws:///inspector",  // see https://github.com/facebook/stetho/issues/403
        "devtoolsFrontendUrl": "http://chrome-devtools-frontend.appspot.com/serve_rev/@188492/devtools.html?ws=%2Finspector"
    }
]
```

**Comment by auchenberg** [comment]
For now the decision is to keep this particular debugger specific to Google Chrome in order to keep configuration to a minimum.

To enable debuggers of other CDP-compliant runtimes such as Electron or Stetho, we have introduced https://github.com/Microsoft/vscode-chrome-debug-core, which is a core library that can be used to make a new stetho-specific debugger.

As you can see in https://github.com/Microsoft/vscode-chrome-debug/blob/master/src/chromeDebug.ts#L11, this debugger doesn't actually do much, as most of the logic is inside our core debugger. It should be straight forward to introduce `vscode-stetho-debug`

**Comment by auchenberg** [comment]
We might be able to provide "one unified debugger" down the road, but for know, we'd like to keep the experience as simple as possible, and specific to Google Chrome.
