### ISSUE TITLE
Improve telemetry to get better understanding of usage

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug#215]
Improve telemetry to get better understanding of usage:
- [ ] Count of debuggable targets detected (result from `/json`) 
- [x] Send event every time the debugger is started 
- [x] Send event every time the debugger is stopped
- [x] Send event for each debugger action (step-in, etc)
- [x] Add option to opt-out of telemetry. See https://github.com/Microsoft/vscode-react-native#disable-telemetry-reporting
- [ ] Can we also get to know what the filetype is for toggled breakpoints (ts, js, mjs, etc)?

Inspiration:
https://github.com/Microsoft/vscode-react-native/blob/master/src/common/telemetry.ts

**Comment by roblourens** [comment]
This turned out to be relatively easy for first-party extensions - I added telemetry events for the above and it should start showing up in our Kusto store as soon as an update goes out. It will show up for both chrome-debug and node-debug2, and will include the extension id to distinguish them. Might be delayed by a day or two though. @auchenberg ping me if you need to know where to find this telemetry.

Opt-out will follow the general vscode telemetry opt-out switch since it goes through the same system.

**Comment by auchenberg** [comment]
Great @roblourens! Is it possible to add telemetry for the 1)  and 6) options too?

**Comment by roblourens** [comment]
Uh, I did! :)

**Comment by auchenberg** [comment]
Ahh. Love it! You rock @roblourens  🎉💪🏼🎈
