### ISSUE TITLE
runtimeArgs incorrectly parsed

### ISSUE THREAD

**Issue by ericvana** [Microsoft/vscode-chrome-debug#246]
Hi,

When using the runtimeArgs parameter in launch.json, all characters of the value are space separated on the command line, instead of a single value.

**Comment by roblourens** [comment]
What do you mean by that?

**Comment by ericvana** [comment]
Within vscode, I have this configured as for debugging in my launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://192.168.2.1:5000/tests/index.html",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
            "userDataDir": "${workspaceRoot}/.vscode/chrome",
            "runtimeArgs": "--disable-infobars"
        }
    ]
}
```
When I start debugging, chrome is started, but the runtimeArgs parameter is not passed to chrome as "--disable-infobars" but as "- - d i s a b l e - i n f o b a r s".

As can be seen [here](http://i.imgur.com/pmeZDfg.png) from the Task Manager on Windows 8.1.

**Comment by roblourens** [comment]
This is probably because runtimeArgs should be an array, not a string. That value should have a squiggly underline with some warning about that. Works for me when I use `"runtimeArgs": ["--disable-infobars"]`

![image](https://cloud.githubusercontent.com/assets/323878/19180815/9d0dc12a-8c1d-11e6-8c5a-3a7726afc1a8.png)
