### ISSUE TITLE
Running the debugger with inline sourcemaps?

### ISSUE THREAD

**Issue by variuse** [Microsoft/vscode-chrome-debug#272]
I'm currently trying to get the debugger running with a regular Angular 2 / TypeScript project based on Angular Seed (https://github.com/mgechev/angular-seed). Connection to Chrome works fine, unfortunately I'm still getting "_Breakpoint ignored because generated code not found (source map problem?)._" when trying to stop at breakpoints in VSCode.

My launch.json looks like this:
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "url": "http://localhost:5555"
        }
    ]
}`

The angular seed generates inline sourcemaps. Does the plugin support these anyway? If yes, how should it be configured? There's nothing I could find the docs. 

I also tried to change the sourcemaps generation to external *.map files, but still getting the same error messages. Which parameters would be necessary for external sourcemaps (sourceRoot? etc.?)?

Thanks a lot!

**Comment by TimBo93** [comment]
Yes inline sourcemaps should work. 
I am using webpack and it works with inline source maps as well as with "normal" source maps.

**launch.json**
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch index.html with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:12345/index.html",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}
```

You said, your connection works. Do you get some debug messages and other stuff inside your console and can you reach [http://localhost:9222/]() ?

**Comment by roblourens** [comment]
@variuse I tried out angular-seed, but the sourcemap config is wrong. Let me explain what the problem.

The first thing you need to do is set `"webRoot": "${workspaceRoot}/src/client"` because the webserver is serving scripts out of there.

It still doesn't work, so I look at the diagnostic logs and see

```
SourceMap: creating for http://localhost:5555/app/app.component.js
SourceMap: sourceRoot: undefined
SourceMap: sources: ["app/app.component.ts"]
SourceMap: webRoot: /Users/roblou/code/angular-seed/src/client
SourceMap: no sourceRoot specified, using webRoot + script path dirname: /Users/roblou/code/angular-seed/src/client/app
SourceMaps.scriptParsed: http://localhost:5555/app/app.component.js was just loaded and has mapped sources: ["/Users/roblou/code/angular-seed/src/client/app/app/app.component.ts"]
```

The 'sources' entry in the sourcemap is wrong, because it is supposed to be resolved relative to the js script, but the result is that there are two `/app` in the resulting path. If you debug this with sourcemaps in chrome devtools, you see an incorrect path with '/app/app` too. That's just how it's supposed to be resolved.

There are two ways you can fix this. One is two change `build.js.dev.ts` in the project, and set `...sourcemaps.write({sourceRoot: '/'})`, so that the 'sources' will be resolved relative to the server root, which I think was their intention. In fact, in that file there's a commented out section that references debugging in webstorm, so someone knows about this problem. 

The second way is by using 'sourceMapPathOverrides', like this:
```
"sourceMapPathOverrides": {
    "app/*": "${webRoot}/app/*"
}
```

This says that when the sourcemap says the path is `app/<something>`, the actual path on disk is `${webRoot}/app/<something>`. 

With either of these fixes, I can debug an angular-seed project. Please try it out and let me know.

**Comment by variuse** [comment]
@roblourens Both of your suggestions work perfectly! Thanks so much!
