### ISSUE TITLE
Console intellisense does not work when connected to chrome

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode-chrome-debug#285]
![image](https://cloud.githubusercontent.com/assets/1018196/20243632/dfc5de12-a914-11e6-8360-ad1071bea4fd.png)

docume should autocomplete to 'document'

**Comment by roblourens** [comment]
Does any intellisense work or just this? Works on my machine?

**Comment by roblourens** [comment]
Does any intellisense work or just this? Works on my machine?

**Comment by nojvek** [comment]
Tried updating all chrome, vscode, vscode chrome extension. Same issue.

OS: OSX 10.9.5
Chrome: Version 54.0.2840.98 (64-bit)
VSCode: 1.7.1
Extension: 2.2.2

Same issue:

![image](https://cloud.githubusercontent.com/assets/1018196/20319734/1dc65ca8-ab24-11e6-8560-750dfb97f900.png)

Verbose diagnostics logging also shows no messages related to console intellisense. 

![image](https://cloud.githubusercontent.com/assets/1018196/20319934/e03725ce-ab24-11e6-9d30-83dc48f7428e.png)

**Comment by roblourens** [comment]
Dang, you are quite right. I think it's an issue in vscode, though.

@isidorn can you take a look? Oddly enough it works in node2.

I debugged to https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L356 and saw the capabilities missing 

![image](https://cloud.githubusercontent.com/assets/323878/20552486/6689bf5c-b100-11e6-814f-6fa94ea76681.png)

**Comment by isidorn** [comment]
@roblourens created a pull request #293 and assigned to you to review.
@weinand due to issues like this I am +1 for dropping `supportsCompletionsRequest` flag and that vscode always sends the completions request, if it returns a failure we just silently swallow the error and return an empty array as a completion. My motivation is having the least number of capabilites as possible - if that makes any sense.

**Comment by weinand** [comment]
@isidorn since we haven't explicitly specified how a debug adapter deals with unrecognised requests, we cannot drop any of the `supportsXxxxRequest` flags. Yes, the default implementation in the npm module returns an error for unrecognised requests, but debug adapters using a different library might behave differently. Imagine a debug adapter that just crashes upon receiving an unknown request. That would render the debug adapter unusable.

**Comment by roblourens** [comment]
@isidorn, that's already set here, https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/chromeDebugAdapter.ts#L175. I checked that it's sent in this case, and this works for node-debug2 using the same code.

**Comment by roblourens** [comment]
This works for me when paused, but I don't get the completions request when not paused. Can you try that? That's supposed to work, right?

**Comment by isidorn** [comment]
@roblourens currently the feature is implemented in such a way that it only works when paused. 
Created https://github.com/Microsoft/vscode/issues/16139 to track this

**Comment by roblourens** [comment]
Oh right, I forgot. I assume that was @nojvek's problem.
