### ISSUE TITLE
sourceMapPathOverrides defaults don't work as expected

### ISSUE THREAD

**Issue by mherodev** [Microsoft/vscode-chrome-debug#361]
I'm generating a simple React application that renders out to a `bundle.js` via webpack. 

For some reason, despite the `sourceMapPathOverrides` defaults, I still needed the following line for my source maps to be picked up by VS Code's debugger:

`"sourceMapPathOverrides": { "webpack:///*": "${webRoot}/*" }`

Why this line isn't covered by the defaults, I don't quite understand, but it seems like a bug:

```
"sourceMapPathOverrides": {
    "webpack:///./*":   "${webRoot}/*", // Example: "webpack:///./src/app.js" -> "/users/me/project/src/app.js"
    "webpack:///*":     "*",            // Example: "webpack:///C:/project/app.ts" -> "C:/project/app.ts"
    "meteor://💻app/*": "${webRoot}/*"  // Example: "meteor://💻app/main.ts" -> "c:/code/main.ts"
}
```

The only change here is getting ridding of the `.` before the key path.

**Comment by mherodev** [comment]
For reference, the relevant source files are in fact in `./src`.

**Comment by roblourens** [comment]
The problem is that `"webpack:///*":     "*"` is already set. If that code was a little smarter, it might try the first, see that it doesn't work, then move on to the second. I have that pattern because it's a common default for some setup.

This also came up in #315. I hope to do something about it some day. Glad you were able to figure it out though!
