### ISSUE TITLE
Redundant breakpoints appear in editor after hitting

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode-chrome-debug#402]
- VS Code Version: 1.11.1
- OS Version: Windows 10 x64

Steps to reproduce:

1. Clone `https://github.com/akveo/ng2-admin/`
2. `npm install`
3. Set breakpoint in `src\app\pages\tables\components\smartTables\smartTables.component.ts` at the lines 68-71
4. `npm start`
5. Launch debug configuration `Launch Chrome against localhost, with sourcemaps`
6. Proceed to page `http://localhost:3000/#/pages/tables/smarttables`
7. Refresh the page

![capture](https://cloud.githubusercontent.com/assets/4777512/24841739/6b15f13a-1d93-11e7-8929-5d7979c76949.PNG)

**Comment by roblourens** [comment]
I see you're using `devtool: 'cheap-module-source-map'`, which tends to cause issues. You might have better luck with a less aggressive setting. I see similar issues with Chrome Devtools, and loading the sourcemaps in a visualizer, the mappings are all screwed up in that part of the file.

This issue is tracking these issues on Webpack's end: https://github.com/webpack/webpack/issues/2145

**Comment by mattflix** [comment]
I see this issue too and I'm not using "cheap-module-source-map", nor Webpack.

I'm using Babel and Browserify.

**Comment by auchenberg** [comment]
This seems to be a new issue related to column breakpoints. Why is the breakpoints shown twice @roblourens? I didn't see this before in v2.x.x releases.

**Comment by roblourens** [comment]
I'm not sure whether the original issue was for the breakpoints showing up inline, or the fact that there are 5 breakpoints on line 69. The breakpoints showing up inline when you refresh the page is  a bug since I meant to hide them in that case since column BPs aren't implemented yet, but they will come back when I implement column BPs. I can reopen this to fix that but column BPs will probably come for real soon.

**Comment by Deilan** [comment]
@roblourens Just in case if that was not in scope of the fix, otherwise please ignore: the following phantom breakpoint appeared after I changed the code in a debugging session and the app recompiled and reloaded (Angular CLI based):

![redundant breakpoint](https://cloud.githubusercontent.com/assets/4777512/25369622/f02dab50-298d-11e7-83ec-08406acdb27a.png)

**Comment by roblourens** [comment]
Yeah, that's what I was thinking of - should be fixed soon from the discussion in https://github.com/Microsoft/vscode/issues/24963
