### ISSUE TITLE
remap ~ to node_modules doesn't work for mean stack

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode-chrome-debug#406]
Re https://github.com/Microsoft/vscode/issues/22279

While testing against mean stack, we found that webpack maps `node_modules` folder to `~` however we can't make Chrome Debugger take this mapping.

**Comment by roblourens** [comment]
I thought we got it to work? Can you show me what you tried and how it didn't work?

**Comment by roblourens** [comment]
Nvm, I remember, and I tried it on a MEAN app and found that in `gulp/development.js` I have to change `webpackConfig.devtool = 'eval';` to `webpackConfig.devtool = 'source-map';`, otherwise debugging doesn't really work anywhere, since there aren't sourcemaps from webpack.

Once I do that, I can debug node_modules fine with the right mapping. And I'm adding a ~ mapping by default.
