### ISSUE TITLE
Disable Chrome session restore prompt

### ISSUE THREAD

**Issue by Deilan** [Microsoft/vscode-chrome-debug#416]
- VSCode Version: 1.11.2
- OS Version: Windows 8.1 x64
- Debugger for Chrome version: 3.0.1
- Chrome version: 58.0.3029.81
- Language: TypeScript 2.2

Please find a way to disable chrome's session restore warning that occurs on every launch after the previous debugging session was finished. It's very annoying. At least for a case when `userDataDir` setting is there. `runtimeArgs` such as `--disable-session-crashed-bubble` and `--disable-infobars` don't help.

**Comment by roblourens** [comment]
Agreed. I had tried those args. I don't know if there's a friendlier way to kill it.

Workaround: Run the launch config, open chrome devtools on that tab. Debugger detaches but won't kill Chrome. Next time you run a launch config and stop, Chrome will stay open. (Or launch it in debug mode manually and use 'attach')

**Comment by Deilan** [comment]
@roblourens I've seen the following workaround on StackOverflow: [How to disable Chrome's session restore warning using nodejs?](https://stackoverflow.com/questions/38870284/how-to-disable-chromes-session-restore-warning-using-nodejs). Perpharps it could help.

**Comment by aj-r** [comment]
That workaround doesn't work for me. I can't add it as a preLaunchTask, because I already have a preLaunchTask that runs as a background task. This means that it only runs the first time I launch chrome - after that it continues running in the background (even when I stop debugging).

**Comment by aj-r** [comment]
This error message seems to only happen if I stop debugging while execution is paused (i.e. a breakpoint is triggered). Here are some steps that can reproduce the issue consistently (using Windows 8.1, Chrome 64):

1. Launch debugger and close Chrome normally using Chrome's "x" button (to reset chrome's state)
2. Set a breakpoint somewhere that will be hit
3. Launch the debugger and wait for the breakpoint to be hit
4. *Without pressing Continue*, press the Stop button in VS Code.
5. Launch the debugger again - the error prompt appears in chrome.

So it seems that chrome is not being shut down properly if code execution is paused. Ideally we should be able to change how chrome is shut down in this case (maybe continue execution as if the user pressed F5, then close chrome?).

Note: if I use Chrome's "x" button in step 4 (instead of VS Code's Stop button), chrome shuts down normally and I get no notification. So maybe we should start by trying to close chrome nicely (send a nice shutdown signal), and if chrome doesn't shut down right away, then force kill it or whatever you do now.

This is by far the most annoying issue I have with `vscode-chrome-debug`. I hope it can be fixed soon.

**Comment by auchenberg** [comment]
A PR for this would be much appreciated!

**Comment by roblourens** [comment]
I agree that continuing before killing Chrome is the right thing to do.

**Comment by aj-r** [comment]
Ok, I tried adding `this.continue(true);` right before `super.disconnect(args);` (https://github.com/aj-r/vscode-chrome-debug/commit/3af4129a4ee972f44b62b2977cac7c9e269ed29b), but that doesn't seem to fix the problem consistently. In fact, sometimes I still get the session crashed message even if I stop debugging while it's NOT paused. So it looks like this bug is not as consistent as I thought earlier.

I'm going to they the second approach of nicely shutting down chrome (instead of force killing it - only force kill it if the nice kill didn't work). Will need someone to test this on Mac/Linux though.

**Comment by murugaratham** [comment]
+1 to this, not a show-stopper, but a QOL tweak for OCD
