### ISSUE TITLE
urlFilter not filering targets in pickProcess dialog for attach

### ISSUE THREAD

**Issue by ButuzGOL** [microsoft/vscode-chrome-debug#438]
- VS Code Version:
Version 1.12.2 (1.12.2)

Steps to reproduce:

1. set urlFilter to "github"
2. press debug
3. all tabs shown

**Comment by jbsulli** [comment]
I'm seeing this as well. Did this issue get missed last June?

**Comment by nistvan86** [comment]
Have the same issue. Trying to debug Electron render process with the extension, but providing `"urlFilter": "*/src/index.html"` has no effect, still all available tabs are shown instead of auto-attaching.

![image](https://user-images.githubusercontent.com/829428/36937244-ab99f8ee-1f10-11e8-8910-271912cbd9bd.png)

**Comment by roblourens** [comment]
It is only used for launch currently. For now you can use "url"

**Comment by connor4312** [comment]
This is fixed in our [new debugger](https://github.com/microsoft/vscode-js-debug/), in the non-default `targetSelection: pick` mode.
