### ISSUE TITLE
Breakpoint ignored because generated code not found(source map problem?)

### ISSUE THREAD

**Issue by ShocKwav3** [Microsoft/vscode-chrome-debug#477]
- VS Code Version: 1.15.0

Steps to reproduce:

Tried to debug a react program.
![untitled](https://user-images.githubusercontent.com/23660537/29342204-2bc752c2-8232-11e7-8dc0-b6f7097f540a.png)

**Comment by auchenberg** [comment]
Can you try to add the `"trace": "verbose"` option to `launch.json` and paste the output from the Debug Console in here? It looks like a source mapping issue

**Comment by elghali** [comment]
@auchenberg having the same issue with the following output:

`From client: setBreakpoints({"source":{"path":"c:\\Users\\developer.CTServ\\Desktop\\React\\MyProject\\src\\views\\components\\PE\\RESP.js","name":"RESP.js"},"lines":[20],"breakpoints":[{"line":20}],"sourceModified":false})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"setBreakpointsRequest","data":{"fileExt":".js"}}}
To client: {"seq":0,"type":"response","request_seq":10,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":20,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1006}]}}`

**Comment by roblourens** [comment]
@ShocKwav3 It looks like bundle.js doesn't have a sourcemap, please check your config and post the log here if you need more help.

@elghali Please see the section on the `.scripts` command in the readme, try that, and post a new issue if you can't figure it out.
