### ISSUE TITLE
Breakpoint ignored because generated code not found(source map problem?)

### ISSUE THREAD

**Issue by m0hs3n52** [Microsoft/vscode-chrome-debug#586]
![image](https://user-images.githubusercontent.com/15187351/35247681-77be8874-001f-11e8-8d40-212d82ef47ed.png)

- VS Code Version:
1.19.2

i'm trying to run debug on VS Code but the break point showing in gray color and say "Breakpoint ignored because generated code not found)".

i would appreciate if you can help me with that.

**Comment by auchenberg** [comment]
Try setting your `webroot` to `#${workspaceFolder}/site/src` or where your source files are located in relation to most likely your webpack config,

**Comment by m0hs3n52** [comment]
i've changed it to `#${workspaceFolder}/site/src`  but still didn't work. i also tried `#${workspaceFolder}/src` didn't worked.

**Comment by auchenberg** [comment]
Have you followed the guide in the readme? https://github.com/Microsoft/vscode-chrome-debug#the-scripts-command

It's most likely because your `webRoot` is configured wrong, and you can run the `.scripts` command after each time you change it, to see how the mapping is between your filesystem and the loaded scripts. The path in brackets () for a given file needs to match the files on desk before you can set a breakpoint in them.

Your `webroot` shouldnt contain `#` but probably be something like `${workspaceFolder}/site/src`

**Comment by m0hs3n52** [comment]
Thanks @auchenberg.
i tried everything for `webRoot` but none of the worked. i ran `.scripts` command for each of them but it doesn't show the filesytem inside ().

anything else that i can try?

**Comment by auchenberg** [comment]
@m0hs3n52 Can you tell us more about your overall setup? Could be a problem with your webpack config.

**Comment by auchenberg** [comment]
Can you try setting your `devtool` to `source-map` to get webbpack to generate a more detailed sourcemap

**Comment by m0hs3n52** [comment]
Thanks a lot @auchenberg it did work.
i've change the `devtool` to `source-map` so i can see the localpath inside () now. Then change the `webRoot` to `${workspaceFolder}/site` and it start hitting the breakpoints.

**Comment by auchenberg** [comment]
Yay 🎉  Glad you got it working @m0hs3n52
