### ISSUE TITLE
Attach only attaches to first tab/dom in debug session with --remote-debug-port

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode-chrome-debug#66]
Working with multi browser tab application such as CEF. this is a showstopper. 
Need a way to specify the numerical offset in the launcher or named instance of session
See screens below.
![image](https://cloud.githubusercontent.com/assets/1707226/11731181/5c5ab360-9ffe-11e5-898b-881f41d36f3c.png)
![image](https://cloud.githubusercontent.com/assets/1707226/11731204/84290d2e-9ffe-11e5-8af8-68888c657445.png)

**Comment by roblourens** [comment]
Would specifying the url of the tab be ok? I think the order of targets that chrome gives doesn't always match the order of tabs.

**Comment by justin-romano** [comment]
I think so. i havent looked at the debugger code for chrome so im not certain how it works. Looks like you would need to know that guid shoved in the parameters though right?
(Excellent extension BTW, if it did not exist i was going to write it, loving using it)

**Comment by roblourens** [comment]
For a 'launch' config, I search for a target that has the url I just launched, then grab the websocket url with the guid. I could do the same for an attach config, search for a target with specified url.

And thanks!

**Comment by auchenberg** [comment]
@justin-romano Did specifying a `url` do the trick for you?

**Comment by collinksmith** [comment]
+1. As you suggested @roblourens, I think it would be very nice to be able to set a url for the attach config, just as you currently can for the launch config. As it is now, if you've opened other tabs in chrome since you opened your test page, you need to re-open a new tab and load the page every time you run the debugger.

**Comment by felixfbecker** [comment]
@roblourens Yes, please look for the URL. But maybe fallback in case no URLs match:
 - if a URL matches except the hash, take that
 - if a URL matches except the query, take that
 - if a URL matches except the path, but domain/IP, take that (for VirtualHost configurations)
 - if none match, attach to the first tab, but maybe print a warning

otherwise it could be annoying to always have to navigate back to the index state of your app so the debugger recognizes the tab.

**Comment by justin-romano** [comment]
Has that feature been added? Will give it a go
