### ISSUE TITLE
Support different consoles in launch.json configuration

### ISSUE THREAD

**Issue by stefanocrosta** [Microsoft/vscode-chrome-debug#679]
The current Debug Console does not support colours (see #537 and #282).

Is it possible to support alternative consoles (internalConsole and externalConsole, see https://code.visualstudio.com/docs/editor/debugging#_launchjson-attributes) in launch.json configuration? 

Thanks

**Comment by roblourens** [comment]
The debug console does support terminal color codes (#537 was wrong) so this just needs to map color commands from Chrome to terminal color codes. We won't be able to show the exact color specified, and will need to keep a mapping of css colors like "seagreen" to some terminal color code.

If you're asking to log to the terminal instead of the debug console, I don't think that helps anything and isn't really possible. Node writes to the process' stdout so its output will show up in the terminal that it was launched in. Scripts on a webpage don't send output to Chrome's stdout.
