### ISSUE TITLE
Cannot find Chrome on macOS when not in `/Applications`

### ISSUE THREAD

**Issue by neknalb** [microsoft/vscode-chrome-debug#700]
- VS Code Version: 1.25

Steps to reproduce:

1. Running macOS; having installed "Google Chrome.app" somewhere else then `/Applications/` (e.g. in `~/Applications/`)
2. Create a launch config like
    ```
    {
      "name": "Debug DevServer",
      "type": "chrome",
      "request": "launch",
      "sourceMaps": true,
      "url": "http://localhost:8080"
    },
    ```
3. -> `[debugger-for-chrome] Error processing "launch"…` … cannot find chrome.

-------

In our development team different members have "Google Chrome.app" installed in different locations. debugger-for-chrome looks for the Chrome only in the `/Applications` folder. I know it's possible to specify another location by configuring a `runtimeExecutable` path. But 1.) other tools (e.g. webpack devServer) are able to do that, and 2.) since the launch config is in our git its a bad place for developer-specific settings.

**Comment by roblourens** [comment]
Where is it installed?

**Comment by neknalb** [comment]
E.g. in `~/Applications/`

**Comment by roblourens** [comment]
Is it enough to add `~/Applications` to the list of places to search, or should it be able to search in arbitrary paths? Not sure exactly what webpack does.

**Comment by neknalb** [comment]
The Chrome app should be found in any (typical?) place. webpack does it somehow.

The information to find Chrome does exist. A call to open some file with some given app via Terminal can do this as well. E.g.`open someFile.html -a Google\ Chrome` or `open README.md -a Visual\ Studio\ Code`.

**Comment by roblourens** [comment]
I've been meaning to switch to a better browser opener package, looks like webpack-dev-server uses https://www.npmjs.com/package/opn

**Comment by roblourens** [comment]
Would take a PR for this too

**Comment by scovic** [comment]
I have the same problem
VS Code Version: 1.26.1
OS: Linux Mint

My launch config:
```
{
 "version": "0.2.0",
    "configurations": [
     {
          "name": "Chrome",
          "type": "chrome",
          "request": "launch",
          "runtimeExecutable": "google-chrome",
          "url": "http://localhost:3000",
          "webRoot": "${workspaceRoot}/src"
      }
    ]
}
```

I'm trying to debug react app, when i start debugging i get this:
Attribute 'runtimeExecutable' does not exist ('google-chrome')

I tried with /usr/bin/google-chrome, i get same message.

**Comment by jamesseanwright** [comment]
@roblourens is anyone working on the fix you suggested? I'd be more than happy to submit a PR!

**Comment by roblourens** [comment]
Go for it!

**Comment by jamesseanwright** [comment]
Great, I'll take a look this evening and keep you posted! Feel free to add me as an assignee if it makes clear that someone is now working on this. Thanks :)

**Comment by jamesseanwright** [comment]
I've cloned this repo and am able to reproduce this issue locally. I'll take a look at this over the next few days and keep you posted.

**Comment by jamesseanwright** [comment]
It turns out that replacing the existing logic with a package such as `opn` wouldn't be so trivial, given the Windows-specific code in the current solution (e.g.`spawnChromeUnelevatedWithWindowsScriptHost`). I'm thus leaving that intact but trading the macOS and Linux paths for `open -a` and `xdg-open` respectively (à la `opn`.) I'll update you once this is working, at which stage I'll test macOS and a handful of Linux distros.

**Comment by jamesseanwright** [comment]
I've raised a PR to fix this: check out #740!

It turns out that xdg-open isn't an appropriate choice to achieve the same in Linux, so I've left the path intact for now. Let me know if you need anything else!

**Comment by roblourens** [comment]
What's the problem with `xdg-open`?

**Comment by jamesseanwright** [comment]
`xdg-open` only allows one to open a file or URL using the preferred application configured by the user/system; it doesn't have the capability of opening a specific application by name (à la `open -a` on macOS.)

More info is provided by [`man xdg-open`](https://linux.die.net/man/1/xdg-open).

**Comment by roblourens** [comment]
Got it, thanks.

I'm testing this and having an issue with launching a new Chrome instance when an instance is already running. We pass `--user-data-dir` to open with a new profile, because if chrome is already running, it won't switch into debug mode when we start with `--remote-debugging-port`. 

I see we start with `open -a google chrome --args --remote-debugging-port=9222 --no-first-run --no-default-browser-check --user-data-dir=/var/folders/tx/p0ycbfpj37786p760wwdg6y80000gn/T/vscode-chrome-debug-userdatadir_9222 about:blank` but when chrome is already running, it focuses the existing app instead of starting one with the user-data-dir. Any idea how to make that work?

**Comment by jamesseanwright** [comment]
Oops! Apologies for the oversight!

It seems [`open` supports an `-n` flag](http://osxdaily.com/2011/05/11/multiple-instances-application-mac/) for creating new instances of already-open apps. I can take a look at this tomorrow (I'm based in the UK so it's getting on a bit!)

**Comment by jamesseanwright** [comment]
Looks like the `-n` flag does the trick; I'm able to launch an entirely separate, debuggable Chrome instance with a temp profile.

Let me know if you encounter any other issues on your end.

**Comment by neknalb** [comment]
Hi @roblourens and @jamesseanwright ,

I'm happy to see you working on this issue. Looking forward for your solution!

**Comment by jamesseanwright** [comment]
I have a potential workaround up my sleeve that will be path-agnostic _and_ will allow us to completely control the underlying process. I'll try to take a look over the next few days.

**Comment by jamesseanwright** [comment]
Unfortunately, the aforementioned workaround isn't feasible. I was going to use a plist parser to determine the location of the Chrome app, but no available parsers support the binary plist format.

With this in mind, I'm all out of ideas, and sadly won't be able to dedicate any subsequent time to this.

**Comment by roblourens** [comment]
Sorry it didn't work out, thanks for your effort in investigating this.

**Comment by connor4312** [comment]
We've since moved to a new debugger with a new discovery mechanism -- by default, we query OSX launchservices to discover browsers, so if it's registered there it should be discovery. We also now [support setting a default runtimeExecutable in your user settings](https://github.com/microsoft/vscode-js-debug/issues/836), so if you have chrome installed in a custom way and custom path, you can use that.
