### ISSUE TITLE
Add option to automatically attach to all tabs in window

### ISSUE THREAD

**Issue by mrjones2014** [microsoft/vscode-chrome-debug#719]
- VS Code Version: 1.25.1

In our system, most links to other parts of the system open in a new tab. In this case, I have to manually start a new debugging session and launch the "attach" configuration to attach to the new tab. There should be an option so that new tabs spawned from the currently attached tab are automatically attached to a new debug session if it still matches the `"urlFilter"` configuration property. I'm not sure if this is actually feasible, but I would KILL to have this feature. 

Steps to reproduce:
1. Start debugging with a "launch" configuration
2. Click an application link that opens in a new tab

launch.json
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "urlFilter": "http://localhost:8081/app/*",
      "webRoot": "${workspaceFolder}",
      "sourceMaps": true,
      "breakOnLoad": false
    },
    {
      "type": "chrome",
      "request": "attach",
      "name": "chrome attach",
      "port": 9222,
      "urlFilter": "http://localhost:8081/app/*",
      "webRoot": "${workspaceFolder}",
      "sourceMaps": true
    }
  ]
}
```

**Comment by roblourens** [comment]
This is much like the "auto attach" feature for new processes spawned in terminals for node debugging.

**Comment by artu-ole** [comment]
Nowadays with latest 'js-debug-nightly' v2020.9.2817 the behavior seems to be to connect to all tabs unless `urlFilter` is specified which is different from how previously `url` option would mean it will attach to one tab only.
Has it been a planned and documented change or a side effect?
![Code_AsTO6URyYv](https://user-images.githubusercontent.com/15938416/95173913-042c6400-07c2-11eb-9bf6-1a99545e7cf9.png)

**Comment by roblourens** [comment]
Yes, this is by design

**Comment by artu-ole** [comment]
@roblourens Alright, I must have missed that in the changelogs, do you care to cite it?

**Comment by roblourens** [comment]
cc @connor4312 I'm not sure what to point to

By the way, note that development/issue tracking is now in microsoft/vscode-js-debug, and this repo will be archived soon

**Comment by connor4312** [comment]
This was a tweak we did last month that didn't make the release notes.

The change was made because we had a couple issues come in where people were asking why breakpoints weren't being hit when they opened another window or tab. We decided it's more useful to attach to tabs by default, and users can configure the `urlFilter` more precisely if they don't want this behavior. It's less annoying to have a little visual noise in the sidebar, than it is to try to debug and figure out why things aren't working.

**Comment by artu-ole** [comment]
Okay, makes sense. Do I understand correctly that `url` option now has no effect?
There is a new tab loading speed being slow issue I have when debugger is connected to all tabs without `urlFilter` besides visual noise, but I do run slightly outdated custom chromium build with many extensions - hence I wouldn't necessarily point my finger at the debugger.

**Comment by connor4312** [comment]
That's right. THinking about it some more -- this was a change made for launches where we control the page, but for attachment we're less likely to be the ones owning every tab (since the browser lifecycle is not owned by VS Code). So I think a good change to make is to keep the '*' urlFilter default to attach, but go back to using the url for attachment.

**Comment by artu-ole** [comment]
Thank you, this is a welcome change!
