### ISSUE TITLE
"Other Targets" not working because of "missing features" (Page.enable etc.)

### ISSUE THREAD

**Issue by johannescolmsee** [Microsoft/vscode-chrome-debug#777]
Hello,

I try to use this extension for debugging embedded V8.

After I added the "json" endpoint, the debugger attaches succesfully to my app, however - it transmits commands, which are "Chrome-only" - one example would be "Page.enable".

The commands which are not supported for sure (saw the response in my debug-output):

Page.enable
Runtime.run
Network.enable

I suppose that, if the debugger would ignore those "not supported" features - all would work fine.
An alternative "fix" might be to be able to disable those "chrome-only" settings in launch.json.

**Comment by roblourens** [comment]
This extension only officially supports Chrome and I can't guarantee that it will work with other runtimes. If you are debugging embedded v8, you probably want to use the node debugger instead of the chrome debugger. It doesn't use any of those features and seems like it would be closer to what you are trying to do.

**Comment by johannescolmsee** [comment]
The node debugger did in fact work "better", however - it was far from working (there was absolutely no code visible....all I could do was press "pause", and that did in fact work - it "paused" it)

But that is as far as my experiments with "node-debugging" went.

I will investigate, and if I have positive results, will report back here. (not today though....I am tired...)
