### ISSUE TITLE
Crash when opening Developer tools.

### ISSUE THREAD

**Issue by edvinv** [Microsoft/vscode-chrome-debug#83]
If I start chrome debug session and open Developer tools (F12), chrome and debug session will close. Tested on win10. I'm not 100% sure but I think that this works on Linux.

**Comment by auchenberg** [comment]
This is happening because Chrome currently only supports one concurrent connection. 

There's a bug open for this feature in Chrome: https://code.google.com/p/chromium/issues/detail?id=129539

**Comment by roblourens** [comment]
If you attached to Chrome with an 'attach' config, then this should work - Chrome dev tools will attach and kick out the extension.

If you use a launch config then it will attempt the same thing but when the extension process shuts down, Chrome will die since it's a child process.

If I remember correctly, this was working on OS X but only sometimes working on Windows. I'll leave this open and take another look.

**Comment by edvinv** [comment]
@roblourens great, I hope for solution because this is quite big limitation. Very often when you debug you also need dom explorer, console etc.

**Comment by auchenberg** [comment]
Closing due this is a limitation in Chrome. See my above comment.

**Comment by MartinMa** [comment]
As mentioned by @skolmer in a comment of issue #61 it would be "nice" of VS Code (or the extension) not to engulf Chrome in the abyss, when the extension process goes down.

What speaks against to start Chrome in a detached manner?

Brackets seems to do it that way. The child process, can continue to live, if the debugger is being detached.
![brackets_chrome](https://cloud.githubusercontent.com/assets/123297/13606399/1e5d3658-e54c-11e5-818b-5f49d7c67c5c.png)

**Comment by auchenberg** [comment]
Just so we don't mix the two issues up, there's a new separate bug for the nuking of Chrome processes when debugging is stopped: https://github.com/Microsoft/vscode-chrome-debug/issues/116

**Comment by Spown** [comment]
> Closing due this is a limitation in Chrome. See my above comment.

maybe instead of sweeping it under the carpet and pretending everything is ok we can do something against it? I mean, I get it, you, the developers of this extension can do little about it, but there are other means to solve the problem rather than just by coding. Applying gentle pressure onto Chrome developers to move the issue up the queue is an option too...

At least don't close this issue until someone at Chrome says that it will never be possible to open more than 1 connection.

**Comment by auchenberg** [comment]
@Spown We are working with Chrome team on enabling a better integration with Chrome, but as a 3rd party client to Chromium, there's little we can do other than letting them know that this is a significant problem for our users.

You can help us by putting pressure on Chrome to enable more connections by up-voting this bug, https://bugs.chromium.org/p/chromium/issues/detail?id=129539, and letting them know on Twitter (@ChromeDevTools).

Other debuggers such as vscode-firefox-debug doesn't have the same connection limitations.

**Comment by Spown** [comment]
I've already starred it and I don't use twitter.

vscode-firefox-debug is even more unstable than vscode-chrome-debug and need an additional page reload just to start working.

**Comment by roblourens** [comment]
I think we can at least try to keep the Chrome process open when devtools are opened, and I'm open to suggestions as to why this - https://github.com/Microsoft/vscode-chrome-debug/commit/6ce43189b80f8fac279ba4d29f9c7170eeaf9f80 - doesn't work like it's supposed to.

**Comment by hubplace1** [comment]
I know this issue is now closed, but what about making the launched chrome start with remote debugging enabled and 'under the hood' just attach to that?

**Comment by roblourens** [comment]
That's exactly what it does in launch mode, not sure what you're suggesting.

**Comment by minedeljkovic** [comment]
Good news!
https://developers.google.com/web/updates/2017/10/devtools-release-notes#multi-client
