### ISSUE TITLE
webRoot doesn't support remote development

### ISSUE THREAD

**Issue by jtackaberry** [microsoft/vscode-chrome-debug#832]
When using the new Remote Development feature, webRoot (or pathMapping in general presumably) isn't able to resolve properly when workspaceFolder refers to the remote host.  When workspaceFolder is `/home/me/myproject/` and webRoot is `${workspaceFolder}/web/`, if I set a breakpoint from within Chrome on my Vue application, the file opens in Code as `c:\home\me\myproject\web\webpack:\src\App.vue` .

Consequently, this means breakpoints set within Code on files opened from the remote workspace are always unverified.    On the other hand, I can set breakpoints on this `c:\...\webpack:\...` file (although I'm not actually able to open it from within Code myself -- I have to wait for it to open automagically via a breakpoint set in Chrome).

Code version: 1.34.0-insider (473af33) on Windows 10
vscode-chrome-debug version: 4.11.3

Steps to reproduce:
1. Attach a Remote Development session to a Linux host over ssh
2. Open a workspace containing a web application.  (In my case, it's a Vue application with configureWebpack.devtool = 'source-map' in vue.config.js)
3. Open the chrome debugger on Code
4. Pause (F6) from either within Code or Chrome

Expected result: a file should open in Code relative to `${workspaceFolder}` on the remote host.  I should be able to set breakpoints on this file if I previously opened it from the workspace.

Actual result: a file that's oddly crafted as a local path that doesn't exist (e.g.  `c:\home\me\myproject\web\webpack:\src\App.vue`) is opened instead.  

My launch configuration:
```
    {
      "type": "chrome",
      "request": "launch",
      "name": "vuejs: chrome",
      "url": "http://192.168.0.7:8081",
      "webRoot": "${workspaceFolder}/web/",
      "breakOnLoad": true,
      "sourceMapPathOverrides": {
        "webpack:///./src/*": "${workspaceFolder}/web/src/*",
        "webpack:///././node_modules/*": "${workspaceFolder}/web/node_modules/*",
      }
```

**Comment by roblourens** [comment]
There are a few problems with using the Chrome extension as a UI extension...

- `workspaceFolder` needs to resolve to the full URI: https://github.com/microsoft/vscode-remote-release/issues/270
- The extension needs to handle URIs in some places where it doesn't, and be able to return remote URIs as the source path
- The extension needs to know that it's running in a remote context and not try to resolve paths on linux as `C:\` paths

**Comment by Chuxel** [comment]
@roblourens Just to double check, in order for the extension to connect a local chrome browser window for Docker and SSH, the extension has to run as UI does it not? (Otherwise you debugging port would need to be forwarded from the local side to the remote side, correct?)  The exception here is WSL since all ports are available.

**Comment by roblourens** [comment]
Correct

**Comment by onefork** [comment]
> @roblourens Just to double check, in order for the extension to connect a local chrome browser window for Docker and SSH, the extension has to run as UI does it not? (Otherwise you debugging port would need to be forwarded from the local side to the remote side, correct?) The exception here is WSL since all ports are available.

I have a related question: Does Chrome Debugger in WSL Remote support launching local Chrome out of the box?

Mine will throw `Can't find Chrome - install it or set the "runtimeExecutable" field in the launch config.` . Is this by design?

I had a Chrome Linux install in WSL. So I'm not sure whether my configs are messed up now...

**Comment by roblourens** [comment]
Several ways to do this...

First, to run the Chrome extension as a UI extension, it has to be able to talk to vscode using vscode-remote URIs, and currently it only knows how to deal with paths in the debug protocol, not URIs. This is simple, but it also would need a way to read the remote filesystem to check whether files exist and read sourcemaps. There is an API coming to expose the filesystem provider to extensions, but without that, the experience will be subpar. And to do this, the user has to know whether they want to debug a local chrome or remote chrome (like electron, which I do often) and install the extension in the right place. Also there could be other unforeseen differences because typically the DA runs on the same machine as where the source is located, and I don't know what else will come up.

Second, we could actually run the Chrome extension as a workspace extension, and give it a UI companion extension to launch and manage the Chrome process, and proxy all communication with Chrome through the executeCommand API. This is a bit more complex but also simpler in that the DA would be running in the same location as the source code, and would get normal expected file paths from vscode.

This could work by having the extension start a websocket server on the remote that chrome-debug connects to, or implementing the websocket interface in terms of the DebugSession sendEvent API.
