### ISSUE TITLE
How is this supposed to be set up?

### ISSUE THREAD

**Issue by nitwhiz** [microsoft/vscode-chrome-debug#860]
- VS Code Version: 1.33.1
- Log file (set `"trace": true` in launch config): https://gist.github.com/nitwhiz/9450e3279e1816513ea0dbf30bfe2fc1

Trying to use this whole thing with VueJS and webpack to transpile everything with babel. No vue-cli!

webpack config:

```
const entries = {};
// a bit weird construct to collect entries and make it like 'x/y': '/src/x/y.vue' for each vue file under src/

module.exports = {
	entry: entries,
	plugins: [new VueLoaderPlugin()],
	target: 'web',
	mode: 'development',
	devtool: 'source-map',
	devServer: {
		publicPath: '/dist/',
		contentBase: './prototype/',
		compress: true,
		hot: true,
		port: 9090
	}
	module: {
		// vue loader, babel, ...
	},
	optimization: {
		// some chunks ...
	},
	context: path.resolve(__dirname, 'src/'),
	output: {
		filename: '[name].js',
		library: ['mw3', '[name]'],
		libraryTarget: 'var',
		libraryExport: 'default',
		devtoolNamespace: 'mw3',
		sourceMapFilename: '[name].js.map'
	}
};

```

I followed the basic steps and the ones for vue specific projects but still the config necessary in launch.json is just _weird_.

Aside from webRoot to be set to `${workspaceFolder}/src` while my _web root (aka directory my webpack-dev-server is serving from)_ is `dist/` feeling pretty weird, how is this supposed to work with webpack-dev-server at all?

The logs tell me (and you) at the very bottom (grepped after 'SourceMap') the following:
```
Could not read sourcemap file - ENOENT: no such file or directory, open 'c:\Users\....
```
for every single file **but** the ones **not** in my src/ directory. Not confusing at all.

But why does this work this way anyway, aren't my sourcemaps at `http://localhost:9090/WhatEver.js.map` instead of the disk?

Next, I am supposed to overwrite "some" paths. The word "some" was chosen wise here, because
```
"sourceMapPathOverrides": {
        "webpack:///./src/*": "${webRoot}/*",
        "webpack:///src/*": "${webRoot}/*",
        "webpack:///*": "*",
        "webpack:///./~/*": "${webRoot}/node_modules/*"
}
```
creates just a big WTF in my head. Especially because I have my stuff wrapped in a namespace and I tried various trickeroos to get it in there but nothing works.

Finally, there is `"breakOnLoad": true`, which I read as "as soon as I load something, I will stop the execution and point you to where I currently am in vscode" - nah, it doesn't do anything, true|false won't change anything.

Now I might have gotten some core concepts of webpack/vue/vscode wrong here, but isn't this supposed to work for more than just hello world from an index.js? Because I need no debugger for small projects.

Breakpoints are shown as "defined but not bound" - I have no idea what that even means and why it won't bind anything to them.

I may sound a bit salty and that's because I am. Maybe I'm expecting a bit much but this whole thing actually sounded great in the beginning.

**Comment by roblourens** [comment]
Sorry that it's a pain to set up, basically there are an infinite number of ways to configure sourcemaps in a project and it's impossible for us to know how yours is set up, so it takes some fine tuning per project.

So your sourcemaps have entries like `webpack://mw3.[name]/src/components/list/List.vue`, which, I don't really know where that's coming from but since that doesn't match any of the default sourcemapPathOverride patterns, you probably want

```
"sourceMapPathOverrides": {
    "webpack:///mw3.[name]": "${workspaceRoot}"
```

or something like that to remap that source to `c:\\Users\\an10048\\dev\\mw3-js\\src\\components\\list\\List.vue`. You can use the `.scripts` command to see the real result of this mapping, that's an easy way to debug.

`Finding SourceMap for http://localhost:9090/dist/commons.js by URI: commons.js.map and webRoot/pathMapping: {"/":"c:\\Users\\an10048\\dev\\mw3-js\\src"}` webRoot for you should probably just be `${workspaceRoot}` since dist is in the url.

Your sourcemaps can be accessed from the disk if they are there or downloaded, either is fine but disk is faster. If webRoot is fixed, they will probably be found on disk.

"breakOnLoad" is not "break on anything", see the description. There is also a description here: https://code.visualstudio.com/blogs/2017/12/20/chrome-debugging#_breakpoints-set-before-your-app-runs

**Comment by nitwhiz** [comment]
Kudos to you mate, got it working now. Your suggestions were exactly what I needed. Especially that `.scripts` command (which sadly isn't autocompleted) made debugging this so easy!

Why the webpack-path contains the `[name]` placeholder is a bit weird, but that's an issue on my end.

I thank you in advance!

The **very** easy solution to this looks like this:
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "chrome",
			"request": "launch",
			"name": "mw3-js: chrome",
			"url": "http://localhost:9090/",
			"webRoot": "${workspaceRoot}/",
			"breakOnLoad": true,
			"sourceMapPathOverrides": {
				"webpack://mw3.[name]/*": "${workspaceRoot}/*",
			}
		}
	]
}
```

Dunno why, but `.scripts` told me it's looking for `webpack://` instead of `webpack:///`.

**Comment by roblourens** [comment]
Great, I'm glad it works.

> as it flashes on every script load

It actually should not do that, I will have to look into it.
