### ISSUE TITLE
Add example launch.json configs for sourcemaps

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug#93]
Currently it's too hard to get a working setup going with existing code-base, so we should add example `launch.json` configs for bundling tools that generates sourcemaps:
- Browserify
- WebPack
- RequireJS
- SystemJS
- Gulp SourceMaps

**Comment by roblourens** [comment]
Totally agree. Do you think they should be separate repos, like "vscode-chrome-browserify-boilerplate"?

**Comment by auchenberg** [comment]
I'd just put them inside an `examples` folder, either with a full sample project of a sample bundling config.

Could be useful for testing too.

**Comment by auchenberg** [comment]
Angular + browserify example: https://github.com/auchenberg/timey

**Comment by Growiel** [comment]
Any news on this ? I have a working setup with Angular2 + SystemJS.

My .ts files are in /src, my .js and js.map files are in /app/js. The compiling is working just fine and using the Chrome debbugger in chrome itself also, however if i set a breakpoint with the extension, if never breaks.

This is my launch.json:

`{
            "name": "Angular 2",
            "type": "chrome",
            "request": "launch",
            "url":   "http://localhost:3000/",
            "runtimeArgs": [
                "--new-window", //Open in new window
                "--user-data-dir=C:/dev/", //Can be any directory. Makes chrome load in a different directory so that it opens in a new instance.
                "--remote-debugging-port=9222" //Open in port 9222 (standard chrome debug port)
            ],
            "sourceMaps": true
        },
		{
			"name": "Attach",
			"type": "chrome",
			"request": "attach",
			"port": 9222
		}`

I tried using different configurations for webRoot but to no avail.

**Comment by roblourens** [comment]
I added one. Still thinking about giving them their own repos. We could collect them on a wiki page. Advantages to that system -
* We can fork popular repos, like tutorial/demo apps, and possibly push changes back in via PR, then switch the link from the fork to the officially supported repo 
* If someone else has an app that has a working config, we can add them to the wiki
* Easier for someone else to get started with one - fork one repo, use a normal workflow, instead of working down inside the examples/ directory

On the other hand, it would probably be easier for us to work with all the examples in the same repo. Maybe we can use git submodules for this, but I don't really understand how to use submodules yet.

**Comment by roblourens** [comment]
There are a couple on the wiki Examples page now. Will add more as I go.

**Comment by roblourens** [comment]
Actually I'll leave this open.

**Comment by yacuzo** [comment]
I'd like an example for typescript with sources in a different folder.

**Comment by roblourens** [comment]
I've seen blog posts and other examples out there, which I prefer to building a big list of "official" examples that will go out of date. create-react-app even has an example in their readme. Closing this.
