### ISSUE TITLE
Very difficult to configure VSCode, vscode-chrome-debug, webpack, and webpack-dev-server to work together.

### ISSUE THREAD

**Issue by spersels** [microsoft/vscode-chrome-debug#972]
configure **VSCode**, **vscode-chrome-debug**, **webpack**, and **webpack-dev-server** to work together.

- **vscode**, **vscode-chrome-debug**, and **chrome** by themselves- **easy**

- **webpack** and **webpack-dev-server** .... **no problem**

- hooking them all together so that I can do interactive debugging of the application in vscode - **nightmare.**

I've literally spent hours scouring the web for a single simple example that shows:

1. simple web page (helloworld.html)
2. simple javascript ( helloworld.js --> alert("message"))
3. simple webpack bundling (webpack.config.js) of the helloworld.html, and helloworld.js with source mapping that will work with vscode chrome debugger
4. simple vscode launcher(s) configuration that will a) build the code b) launch webpack-dev-server c) launch Chrome in debug mode pointed at the URL exposed by webpack-dev-server

These tools are so ubiquitous and common, and the ability to interactively debug in this complex environment is so critical.   I'm simply astounded that there aren't a dozen examples of how to do this that just pop up on the first google search.

What am I overlooking?

**Comment by roblourens** [comment]
There are examples out there if you search - the problem is that everyone's webpack configs are different. Usually just comes down to setting the right `sourceMapPathOverrides` for your project. If you tell me what issue you're having in particular I can try to help you out. You can also see if the new experimental debugger https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly works for you, as it handles some cases better than the current one.
