### ISSUE TITLE
The wasm files can't be debugged in vscode

### ISSUE THREAD

**Issue by EKALEB** [microsoft/vscode-chrome-debug#981]
I got the `index.wasm`, `index.wasm.map` and `index.js` generated from `main.cpp`,  but I can't set breakpoints in `main.cpp`. I've checked the content of `index.wasm.map`, it seemed correct to me.
I wonder if the debugger detected `index.wasm.map` from the wasm files. By the way, these files work fine in Chrome Explorers' devtools, and the the breackpoints in `main.cpp` works
[Uploading vscode-chrome-debug.txt…]()

- VS Code Version: 1.42

**Comment by roblourens** [comment]
I have done this before but not for awhile. Could you share the project? Also, would appreciate if you would test this with the new debug adapter that we are working on - https://code.visualstudio.com/updates/v1_42#_new-javascript-debugger

**Comment by EKALEB** [comment]
> I have done this before but not for awhile. Could you share the project? Also, would appreciate if you would test this with the new debug adapter that we are working on - https://code.visualstudio.com/updates/v1_42#_new-javascript-debugger

Would you mind to take a quick look at my project?
https://github.com/EKALEB/test_wasm

**Comment by roblourens** [comment]
Can you debug the main.cpp in the electron developer tools? If it doesn't work there, it won't work in vscode. When I start your project, I see lots of .js and wasm sources but I don't see the .cpp anywhere.

**Comment by RReverser** [comment]
This regression is likely due to https://github.com/microsoft/vscode-chrome-debug-core/issues/547 which VSCode Chrome Debug probably hasn't had a chance to catch up with yet.

**Comment by roblourens** [comment]
@connor4312 does js-debug do what it needs to do here?

**Comment by connor4312** [comment]
Thanks for the tag. I admittedly haven't looked into wasm much/at all yet in js-debug didn't know sourcemaps worked for wasm files -- makes sense though, just bytes instead of characters. I'll move the referenced issue to js-debug and use it as the issue to track wasm support for js-debug. Assuming that we don't want to devote the time to add it to chrome-debug-core which is no longer in use by any active 1st party debugger.

**Comment by RReverser** [comment]
Note that Emscripten and DevTools has been since working on integration of DWARF for richer debugging experience instead of the source map approach; I don't know how it would be possible to implement similar support in VSCode, but perhaps there is a way to make VSCode Chrome Debug and the official C/C++ extension to talk to each other when Wasm is encountered?

**Comment by connor4312** [comment]
Thanks for the heads up!

The approach we've taken for this in similar scenarios--currently for React Native and Blazor--is to have the implementing language [stand up a CDP-speaking proxy](https://github.com/microsoft/vscode-cdp-proxy#vscode-cdp-proxy) that we can connect to. This is not an entirely trivial amount of work, but neither is building a debugger. The main advantages to this are:

- Both DevTools and would VS/VS Code's debugger (or WebStorm or any other CDP-speaking debugger) would work without any specific work on either end.
- It's easy for the proxy to pass-through to the browser with arbitrary smartness and to debug across the wasm world and the DOM/JS world. Additional functionality we might add in the future (e.g. DOM inspector) can be passed through as well.

In DevTools, are you trying to understand DWARF 'natively' or are you some other tool to drive it?

**Comment by RReverser** [comment]
We're doing custom "native" processing, yeah, which in theory could be possible to open-source and reuse in VSCode, but I think using existing DWARF support in the VSCode C++ extension might be more straighforward and in line with users' expectations as it would allow to use same configs and workflow as for regular C++ code.
